version: '2'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db
    ports:
      - '27017:27017'
    networks:
      - common

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --appendonly yes # --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    user: '${UID_GID}'
    ports:
      - '6379:6379'
    env_file:
      - .env
    networks:
      - common

  # nats:
  #     container_name: nats
  #     image: nats:latest
  #     user: "${UID_GID}"
  #     ports:
  #         - 4222:4222
  #     networks:
  #         - common

  # postgres:
  #   container_name: postgres
  #   image: postgres:alpine
  #   volumes:
  #     - ./data/postgresql/pgdata:/var/lib/postgresql/data
  #     # - /etc/passwd:/etc/passwd:ro
  #   # user: '${UID_GID}'
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example
  #   networks:
  #     - common

  mysql:
    image: 'mysql/mysql-server:8.0'
    env_file:
      - .env
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './data/mysql:/var/lib/mysql'
      - >-
        ./config/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - common
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: 'phpmyadmin'
    env_file:
      - .env
    ports:
      - 8080:80
    environment:
      PMA_HOST: '${DB_HOST}'
      PMA_USER: root
      PMA_PASSWORD: '${DB_PASSWORD}'
      PMA_ARBITRARY: 1
      PMA_PORT: '${FORWARD_DB_PORT:-3306}'
    depends_on:
      - mysql
    networks:
      - common

networks:
  common:
    name: common
